version: 1
disable_existing_loggers: False

formatters:
    detailed:
        class: colorlog.ColoredFormatter
        format: '%(log_color)s%(asctime)s %(levelname)s: %(message)s | %(name)s | %(filename)s:%(lineno)d'
        datefmt: '%Y-%m-%d %H:%M:%S'
        log_colors:
            DEBUG:    'cyan'
            INFO:     'green'
            WARNING:  'yellow'
            ERROR:    'red'
            CRITICAL: 'bold_red'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: detailed
        stream: ext://sys.stdout

    # graylog:
    #     class: graypy.GELFTCPHandler
    #     level: INFO
    #     formatter: detailed
    #     host: !ENV ['GRAYLOG_HOST']
    #     port: !ENV ['GRAYLOG_PORT']

    file:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: detailed
        filename: resources/logs/tmp.log
        mode: a
        maxBytes: 10485760  # 10 MB
        backupCount: 5
        encoding: utf8

loggers:
    development:
        level: INFO
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    production:
        level: WARNING
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]