services:
  pg_database:
    image: postgres:latest
    container_name: lake_catalog
    restart: always
    ports:
      - ${PG_ADVERT_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${PG_USER:-pgadmin}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - lake_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: catalog_pgadmin
    restart: always
    ports:
      - ${PGADMIN_ADVERT_PORT:-28888}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER:-pgadmin@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-password}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lake_net
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - ${MINIO_ADVERT_PORT:-9000}:9000
      - ${MINIOCONSOLE_ADVERT_PORT:-9001}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-password}
    volumes:
      - minio_data:/data
    networks:
      - lake_net
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - ${KAFKA_BROKER_PORT:-9092}:${KAFKA_BROKER_PORT:-9092}
      - ${KAFKA_INTERNAL_PORT:-29092}:${KAFKA_INTERNAL_PORT:-29092}
      - ${KAFKA_CONTROLLER_PORT:-19092}:${KAFKA_CONTROLLER_PORT:-19092}
    networks:
      - lake_net
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:${KAFKA_BROKER_PORT:-9092},CONTROLLER://:${KAFKA_CONTROLLER_PORT:-19092},INTERNAL://:${KAFKA_INTERNAL_PORT:-29092}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST_ADDRESS:-172.16.3.246}:${KAFKA_BROKER_PORT:-9092},INTERNAL://kafka:${KAFKA_INTERNAL_PORT:-29092}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:${KAFKA_CONTROLLER_PORT:-19092}
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka_data:/bitnami

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always   
    depends_on:
      - kafka
    ports:
      - ${KAFKA_UI_PORT:-28080}:8080
    networks:
      - lake_net
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${KAFKA_INTERNAL_PORT:-29092}

volumes:
  kafka_data:
    name: kafka_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${KAFKA_VOLUME_DIR:-./kafka_data}
  pg_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PG_VOLUME_DIR:-./pg_data}
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PGADMIN_VOLUME_DIR:-./pgadmin_data}
  minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MINIO_VOLUME_DIR:-./minio_data}
networks:
  lake_net:
    name: lake_net
    driver: bridge

